name: TestMingus
favicon: null
layout_spectrum: 0.36766
typography_spectrum: 0.85211
title: TestMingus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23222a'
    - '#46454d'
    - '#797979'
    - '#a69e9c'
    - '#e8e7e5'
  brandStrength: 0.8591073080897331
  lightness: 0.6954842768609524
  saturation: 0.7469986299984157
  rhythmicContrast: 0.49349598586559296
purpose: []
